export const API_URL = "http://ec2-51-20-114-78.eu-north-1.compute.amazonaws.com:9090/api/v1.0/"
export const API_URL_AUTH = API_URL+"auth"
export const API_URL_MUSIC = API_URL+"music"
export const API_URL_WISHLIST = API_URL+"wishList"
export const API_URL_USERPROFILE = API_URL+"userProfile"
